"""empty message

Revision ID: 0a53ebb3502d
Revises: 3fa0c3bf0d04
Create Date: 2024-11-29 19:31:04.035446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a53ebb3502d'
down_revision: Union[str, None] = '3fa0c3bf0d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('competition_statistics', 'competition_room_data')

    op.add_column('competition_room_data', sa.Column('user_status',
                                                     sa.String, server_default='offline', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_room_data', 'user_status')
    op.rename_table('competition_room_data', 'competition_statistics')
    # ### end Alembic commands ###
