"""empty message

Revision ID: 7e7ae43755b7
Revises: ba26923cbe5e
Create Date: 2024-09-03 16:09:53.053797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7ae43755b7'
down_revision: Union[str, None] = 'ba26923cbe5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_words', 'translation_name', new_column_name='name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_words', 'name', new_column_name='translation_name')
    # ### end Alembic commands ###
