"""empty message

Revision ID: 84fcc9a65ca4
Revises: baa041da1b40
Create Date: 2024-09-29 13:58:37.839945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fcc9a65ca4'
down_revision: Union[str, None] = 'baa041da1b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('rating', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'rating')
    # ### end Alembic commands ###
