"""Added new field in sentence table

Revision ID: 890d791cbdf4
Revises: 9981a619a729
Create Date: 2024-10-10 16:42:19.038705

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '890d791cbdf4'
down_revision: Union[str, None] = '9981a619a729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'level')
    # ### end Alembic commands ###
