"""empty message

Revision ID: aaedd3ccd168
Revises: e2fbe6ad2348
Create Date: 2024-12-04 22:24:16.742276

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaedd3ccd168'
down_revision: Union[str, None] = 'e2fbe6ad2348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.alter_column('users', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
