"""empty message

Revision ID: ba26923cbe5e
Revises: 49cca2fe2652
Create Date: 2024-09-03 14:57:40.056480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba26923cbe5e'
down_revision: Union[str, None] = '49cca2fe2652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'word', new_column_name='name')
    op.alter_column('translation_words', 'word', new_column_name='translation_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'name', new_column_name='word')
    op.alter_column('translation_words', 'translation_name', new_column_name='word')
    # ### end Alembic commands ###
